/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Purchases.java
 *
 * Created on Sep 8, 2011, 8:04:17 PM
 */
package vunafeeds;

import java.sql.*;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Magondu
 */
public class Debtor extends javax.swing.JFrame {
//public static String toEdit;

    /** Creates new form Purchases */
    public Debtor() {
        initComponents();
        Date();
        setLocationRelativeTo(null);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DebtorsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        debtor = new javax.swing.JFormattedTextField();
        debtorName = new javax.swing.JTextField();
        admit = new javax.swing.JButton();
        DisplayDate = new javax.swing.JLabel();
        GenerateAdminNo = new javax.swing.JButton();
        contact = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customer");

        DebtorsPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(110, 189, 235));
        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer Records");
        jLabel1.setOpaque(true);

        jLabel3.setText("Customer ID:");

        jLabel4.setText("Customer Name");

        jLabel5.setText("Contact:");

        debtor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        admit.setBackground(new java.awt.Color(255, 255, 255));
        admit.setText("Save");
        admit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(110, 189, 235), 1, true));
        admit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admitActionPerformed(evt);
            }
        });

        DisplayDate.setBackground(new java.awt.Color(110, 189, 235));
        DisplayDate.setOpaque(true);

        GenerateAdminNo.setText("Generate");
        GenerateAdminNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateAdminNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DebtorsPanelLayout = new javax.swing.GroupLayout(DebtorsPanel);
        DebtorsPanel.setLayout(DebtorsPanelLayout);
        DebtorsPanelLayout.setHorizontalGroup(
            DebtorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DebtorsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DebtorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DebtorsPanelLayout.createSequentialGroup()
                        .addComponent(DisplayDate, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(DebtorsPanelLayout.createSequentialGroup()
                        .addGroup(DebtorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DebtorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contact, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addComponent(debtorName, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DebtorsPanelLayout.createSequentialGroup()
                                .addComponent(debtor, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(GenerateAdminNo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(admit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );
        DebtorsPanelLayout.setVerticalGroup(
            DebtorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DebtorsPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DisplayDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DebtorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(GenerateAdminNo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(debtor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DebtorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(debtorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DebtorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(admit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DebtorsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DebtorsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void Date() {
        Calendar now = Calendar.getInstance();
        int y = now.get(Calendar.YEAR);
        int m = (now.get(Calendar.MONTH)) + 1;
        int d = now.get(Calendar.DATE);
        DisplayDate.setText("Today's date is " + d + " / " + m + " / " + y);
        DisplayDate.setVisible(true);

    }

    private void admitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admitActionPerformed


        //String  = purchase.getText();
        String name = debtorName.getText();
        String id = debtor.getText();
        String cont = contact.getText();
        String status = "Active";
        String statement = null;


        if (name.length() == 0 || id.length() == 0 || cont.length() == 0) {
            JOptionPane.showMessageDialog(null, "Please fill all fields");
        } else {
            try {
                System.out.println("before to edit");


                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/VunaFeeds", "root", "");
                //PreparedStatement psmt = null;
                System.out.println(" Here");


                String editS = HomePage.toEdit;

                if (editS.equalsIgnoreCase("Edit")) {
                    System.out.println("Edit active");
                    statement = "Update Debtor set name = '" + name + "', contact = '" + cont + "' where Customer_ID = '" + id + "' ";
                    PreparedStatement psmt = con.prepareStatement(statement);
                    psmt.executeUpdate();
                } else //(editS.equalsIgnoreCase("Null"))
                {
                    System.out.println("null....");
                    statement = "INSERT into debtor(Customer_ID,name,contact,status) values (?,?,?,?)";
                    PreparedStatement psmt = con.prepareStatement(statement);
                    psmt.setString(1, id);
                    psmt.setString(2, name);
                    psmt.setString(3, cont);
                    psmt.setString(4, status);
                    psmt.executeUpdate();
                }

                JOptionPane.showMessageDialog(null, "Customer details Saved");
                this.dispose();
                HomePage.toEdit = " ";
                Debtor win = new Debtor();
                win.setVisible(true);

            } catch (SQLException e) {

                System.out.println("2 Error : " + e);
                JOptionPane.showMessageDialog(null, "Oops!! An error occured. \n " + e);
            } catch (Exception ex) {
                System.out.println("Error 1:" + ex);
                JOptionPane.showMessageDialog(null, "Oops!! An error occured. \n" + ex);
            }
        }
        // TODO add your handling code here:
}//GEN-LAST:event_admitActionPerformed

    private void GenerateAdminNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateAdminNoActionPerformed

        int IntAdminNo = 0;
        String Customer_ID;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/VunaFeeds", "root", "");
            Statement stmt = con.createStatement(ResultSet.TYPE_FORWARD_ONLY,
                    ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = stmt.executeQuery("Select * from debtor");
            if (rs.last()) {
                String adminNo = rs.getString("Customer_ID");
                IntAdminNo = Integer.valueOf(adminNo);
                System.out.println(IntAdminNo);
                IntAdminNo++;
                Customer_ID = String.valueOf(IntAdminNo);
                debtor.setText(Customer_ID);
            } else {
                IntAdminNo = 1;
                Customer_ID = String.valueOf(IntAdminNo);
                debtor.setText(Customer_ID);
            }

            debtor.setEditable(false);
        } catch (SQLException e) {

            System.out.println("2 Error : " + e);
            JOptionPane.showMessageDialog(null, "Oops!! An error occured. \n " + e);
        } catch (Exception ex) {
            System.out.println("Error 1:" + ex);
            JOptionPane.showMessageDialog(null, "Oops!! An error occured. \n" + ex);
        }
}//GEN-LAST:event_GenerateAdminNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Debtor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DebtorsPanel;
    private javax.swing.JLabel DisplayDate;
    public static javax.swing.JButton GenerateAdminNo;
    public static javax.swing.JButton admit;
    public static javax.swing.JTextField contact;
    public static javax.swing.JFormattedTextField debtor;
    public static javax.swing.JTextField debtorName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
