/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DebtorsPanel.java
 *
 * Created on Nov 14, 2011, 10:07:58 AM
 */
package vunafeeds;

import java.sql.*;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Magondu
 */
public class DebtorsPanel extends javax.swing.JPanel {

    /** Creates new form DebtorsPanel */
    public DebtorsPanel() {
        initComponents();
        Date();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        DisplayDate = new javax.swing.JLabel();
        debtor = new javax.swing.JFormattedTextField();
        GenerateAdminNo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        admit = new javax.swing.JButton();
        contact = new javax.swing.JTextField();
        debtorName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(571, 324));

        jLabel1.setBackground(new java.awt.Color(110, 189, 235));
        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer Records");
        jLabel1.setOpaque(true);

        DisplayDate.setBackground(new java.awt.Color(110, 189, 235));
        DisplayDate.setOpaque(true);

        GenerateAdminNo.setText("Generate");
        GenerateAdminNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateAdminNoActionPerformed(evt);
            }
        });

        jLabel3.setText("Debtor ID:");

        jLabel4.setText("Debtor Name");

        jLabel5.setText("Contact:");

        admit.setBackground(new java.awt.Color(255, 255, 255));
        admit.setText("Save");
        admit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(110, 189, 235), 1, true));
        admit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DisplayDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE))
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(debtorName, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(debtor, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(GenerateAdminNo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(140, 140, 140)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(admit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DisplayDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(debtor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenerateAdminNo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(debtorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void admitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admitActionPerformed
        
        //String  = purchase.getText();
        String name = debtorName.getText();
        String id = debtor.getText();
        String cont = contact.getText();
        String status = "Active";
        
        
        if(name.length() == 0 || id.length() == 0 || cont.length() == 0 ) {
            JOptionPane.showMessageDialog(null, "Please fill all fields");
        } else {
            try {
                
                
                Class.forName("com.mysql.jdbc.Driver");
                Connection con  = DriverManager.getConnection("jdbc:mysql://localhost:3306/VunaFeeds", "root", "");
                PreparedStatement psmt = con.prepareStatement("INSERT into debtor(Customer_ID,name,contact,status) values (?,?,?,?)");
                psmt.setString(1, id);
                psmt.setString(2, name);
                psmt.setString(3, cont);
                psmt.setString(4, status);
                
                psmt.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Customer details Saved");
//                this.dispose();
//                Debtor win = new Debtor();
//                win.setVisible(true);
                
                
            } catch(SQLException e) {
                
                System.out.println("2 Error : "+e);
                JOptionPane.showMessageDialog(null, "Oops!! An error occured. \n "+e);
            } catch(Exception ex) {
                System.out.println("Error 1:"+ex);
                JOptionPane.showMessageDialog(null, "Oops!! An error occured. \n" +ex);
            }
        }
        // TODO add your handling code here:
}//GEN-LAST:event_admitActionPerformed

    private void Date()
{
        Calendar now = Calendar.getInstance();
            int y = now.get(Calendar.YEAR);
            int m = (now.get(Calendar.MONTH))+1;
            int d = now.get(Calendar.DATE);
           DisplayDate.setText("Today's date is " + d + " / " + m + " / " + y);
           DisplayDate.setVisible(true);

}
    
    private void GenerateAdminNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateAdminNoActionPerformed
        
        int IntAdminNo = 0;
        String Customer_ID;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con  = DriverManager.getConnection("jdbc:mysql://localhost:3306/VunaFeeds", "root", "");
            Statement stmt = con.createStatement(ResultSet.TYPE_FORWARD_ONLY,
                    ResultSet.CONCUR_READ_ONLY);
            ResultSet rs =stmt.executeQuery("Select * from debtor");
            if (rs.last()) {
                String adminNo = rs.getString("Customer_ID");
                IntAdminNo = Integer.valueOf(adminNo);
                System.out.println(IntAdminNo);
                IntAdminNo++;
                Customer_ID = String.valueOf(IntAdminNo);
                debtor.setText(Customer_ID);
            } else {
                IntAdminNo = 1;
                Customer_ID = String.valueOf(IntAdminNo);
                debtor.setText(Customer_ID);
            }
            
            debtor.setEditable(false);
        }
        
        catch(SQLException e) {
            
            System.out.println("2 Error : "+e);
            JOptionPane.showMessageDialog(null, "Oops!! An error occured. \n "+e);
        } catch(Exception ex) {
            System.out.println("Error 1:"+ex);
            JOptionPane.showMessageDialog(null, "Oops!! An error occured. \n" +ex);
        }
}//GEN-LAST:event_GenerateAdminNoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DisplayDate;
    public static javax.swing.JButton GenerateAdminNo;
    public static javax.swing.JButton admit;
    public static javax.swing.JTextField contact;
    public static javax.swing.JFormattedTextField debtor;
    public static javax.swing.JTextField debtorName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
