/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Aug 16, 2012, 9:13:08 PM
 */
package vunafeeds;

import java.awt.Desktop;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Magondu
 */
public class Reciept extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public Reciept() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(164, 164, 164).addComponent(jButton1).addContainerGap(181, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(127, 127, 127).addComponent(jButton1).addContainerGap(150, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String[] Description = {"Layers meal", "unga feeds", "dog meal"};
        String[] qty = {"10 kgs", "20 kgs", "10 kgs"};
        String[] rate = {"20", "30", "40"};
        String[] amount = {"200", "600", "400"};
        String total = "12,000";
        String html = "<!DOCTYPE html PUBLIC -//W3C//DTD XHTML 1.0 Transitional//EN http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd>"
                + "<head>"
                + "<meta http-equiv=Content-Type content=text/html; charset=utf-8 />"
                + "<title>Untitled Document</title>"
                + "</head>"
                + "<body>"
                + "<table width=737 border=0>"
                + "<tr>"
                + "  <td width=213><p align=center>PIONEER FEEDS LIMITED</p>"
                + "   <p align=center>P.O BOX 4606-00506</p>"
                + "   <p align=center>NAIROBI-KENYA</p>"
                + "  <p align=center>&nbsp;</p></td>"
                + " <td width=3>&nbsp;</td>"
                + " <td width=507 valign=top><table width=50% border=1 cellpadding=0 cellspacing=0 align=right vspace=0 bordercolor=#000000>"
                + " <tr valign=top>"
                + "   <td>PIN:P0787867767</td>"
                + "  <td>656447675675757</td>"
                + " </tr>"
                + " </table></td>"
                + "</tr>"
                + "<tr>"
                + " <td><table width=200 border=1 cellpadding=0 cellspacing=0 bordercolor=#000000>"
                + "   <tr>"
                + "     <td>Invoice To</td>"
                + " </tr>"
                + " <tr>"
                + "<td><p>2000 Millenium</p>"
                + "  <p>C/O Rachel</p>"
                + " <p>P.O.BoX 65765765 Ngecha</p>"
                + " <p>Tel:0723456432</p>"
                + " <p>Ref no: 000041</p></td>"
                + " </tr>"
                + "</table></td>"
                + " <td>&nbsp;</td>"
                + "  <td>&nbsp;</td>"
                + " </tr>"
                + " <tr>"
                + " <td colspan=3><table width=749 border=1 cellpadding=0 cellspacing=0 bordercolor=#000000>"
                + "   <tr>"
                + "  <td width=745><table width=100% border=1 cellpadding=0 cellspacing=0 bordercolor=#000000>"
                + " <tr>"
                + "  <td width=108><div align=center>Tally Sheet No </div></td>"
                + "<td width=94><div align=center>Date</div></td>"
                + " <td width=92><div align=center>Invoice</div></td>"
                + "  <td width=117><div align=center>Veh Reg No. </div></td>"
                + "<td width=109><div align=center>Appraisal No.</div></td>"
                + " <td width=98><div align=center>Terms</div></td>"
                + "<td width=120><div align=center>Due Date</div></td>"
                + " </tr>"
                + "<tr>"
                + " <td>&nbsp;</td>"
                + "<td>&nbsp;</td>"
                + "<td>&nbsp;</td>"
                + "<td>&nbsp;</td>"
                + "<td>&nbsp;</td>"
                + " <td>&nbsp;</td>"
                + " <td>&nbsp;</td>"
                + " </tr>"
                + " </table></td>"
                + " </tr>"
                + " <tr>"
                + " <td><table width=100% height=256 border=1 cellpadding=0 cellspacing=0 bordercolor=#000000>"
                + "  <tr height=10>"
                + "  <td width=309 height=23><div align=center>Description</div></td>"
                + " <td width=140><div align=center>Qty</div></td>"
                + " <td width=117><div align=center>Rate:</div></td>"
                + "<td width=155><div align=center>Amount</div></td>"
                + " </tr>"
                + "<tr valign=top>"
                + " <td height=229><div style=margin-top:0px; margin-left:0px; margin-bottom:auto;>" + Description[0] + "<br />" + Description[1] + "<br />" + Description[2] + "</div></td>"
                + " <td><div style=margin-top:0px; margin-left:0px; margin-bottom:auto;><div align=center>" + qty[0] + "<br />" + qty[1] + "<br />" + qty[2] + "</div></div></td>"
                + "<td><div style=margin-top:0px; margin-left:0px; margin-bottom:auto;><div align=center>" + rate[0] + "<br />" + rate[1] + "<br />" + rate[2] + "</div></div></td>"
                + " <td><div style=margin-top:0px; margin-left:0px; margin-bottom:auto;><div align=center>" + amount[0] + "<br />" + amount[1] + "<br />" + amount[1] + "</div></div></td>"
                + " </tr>"
                + "  </table></td>"
                + " </tr>"
                + " <tr>"
                + " <td><table width=754 border=1 cellpadding=0 cellspacing=0 bordercolor=#000000>"
                + " <tr>"
                + "<td width=463>&nbsp;</td>"
                + "<td width=121><div align=center><strong>Total</strong></div></td>"
                + " <td width=162><div align=center><strong>" + total + "</strong></div></td>"
                + " </tr>"
                + " </table></td>"
                + " </tr>"
                + " <tr>"
                + "<td>Passed by:.......................................Date:..............................................Authorised By:..........................Date:............... </td>"
                + "</tr>"
                + " <tr>"
                + "<td>Driver's Name........................................................Sign...................................................Date:..................................... </td>"
                + " </tr>"
                + " <tr>"
                + " <td><div align=center>Received above goods in good order and condition.</div></td>"
                + "</tr>"
                + " <tr>"
                + "  <td>Received by: Name................................................Sign....................................................Date....................................... </td>"
                + " </tr>"
                + " </table></td>"
                + "</tr>"
                + "</table>"
                + "</body>"
                + "</html>";

        new File("C:\\VunaReciepts\\Trial\\").mkdirs();
        File htmlFile = new File("C:\\VunaReciepts\\Trial\\core.html");
        htmlFile.mkdir();
        FileWriter writer = null;
        try {
            writer = new FileWriter(htmlFile);
            writer.write(html);
            writer.flush();
        } catch (IOException ex) {
            ex.printStackTrace();
        } finally {
            if (writer != null) {
                try {
                    writer.close();
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        }
        Desktop desktop = Desktop.getDesktop();
        try {
            desktop.print(htmlFile);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Printing failed!", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Reciept().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
