/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SaleItemDialog.java
 *
 * Created on Sep 13, 2012, 7:59:39 PM
 */
package vunafeeds;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.sql.*;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Magondu
 */
public class SaleItemDialog extends javax.swing.JDialog {

    ArrayList<String> cName = new ArrayList<String>();
    ArrayList<String> cNumber = new ArrayList<String>();
    ArrayList<String> pName = new ArrayList<String>();
    ArrayList<String> pNumber = new ArrayList<String>();
    ArrayList<String> available = new ArrayList<String>();

    /** Creates new form SaleItemDialog */
    public SaleItemDialog(java.awt.Frame parent, boolean modal, final JTable table, final ArrayList itemList) {
        super(parent, modal);

        initComponents();        
        populate();
        Date();
        setLocationRelativeTo(null);

        add.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                String particulars[] = addItemToTable();
                if (particulars[0].isEmpty()) {
                    JOptionPane.showMessageDialog(null, "No item found");
                } else {
                    if (itemList.contains(particulars[0])) {
                        JOptionPane.showMessageDialog(null, "That item is already in the sales table", "Error",JOptionPane.ERROR_MESSAGE);
                    } else {
                        int pointer = Tracker.getPointer();
                        table.setValueAt(particulars[0], pointer, 0);
                        table.setValueAt(particulars[1], pointer, 1);
                        table.setValueAt(particulars[2], pointer, 2);
                        table.setValueAt(particulars[3], pointer, 3);
                        table.setValueAt(particulars[4], pointer, 4);
                        String tot = Sale_Table.total.getText();
                        
                        if (tot.equalsIgnoreCase(""))
                        {
                            Sale_Table.total.setText(particulars[3]);
                        }
                        else
                        {
                            double intTot = Double.parseDouble(tot);
                            double intCurr = Double.parseDouble(particulars[3]);
                            intTot = intCurr + intTot;
                            Sale_Table.total.setText(String.valueOf(intTot));
                        }
                        JOptionPane.showMessageDialog(null, "The sale items have been added for sale");
                        Tracker.incrementPointer();
                        
                        itemList.add(particulars[0]);
                        quantity.setText("");
                        rate.setText("");
                        total.setText("");
                        //Total = Total + Integer.parseInt(particulars[3]);
                    }
                }
            }
        });
        //private void addClicked(){}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rate = new javax.swing.JFormattedTextField();
        quantity = new javax.swing.JFormattedTextField();
        product = new javax.swing.JComboBox();
        add = new javax.swing.JButton();
        DisplayDate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        avail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sales Items");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(110, 189, 235));
        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sales");
        jLabel1.setOpaque(true);

        jLabel3.setText("Product ID:");

        jLabel4.setText("Quantity:");

        jLabel5.setText("Rate:");

        rate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rateKeyReleased(evt);
            }
        });

        product.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productActionPerformed(evt);
            }
        });

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        DisplayDate.setBackground(new java.awt.Color(110, 189, 235));
        DisplayDate.setOpaque(true);

        jLabel7.setText("Total Amount");

        total.setEditable(false);

        jLabel8.setText("Available:");

        avail.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DisplayDate, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addGap(43, 43, 43)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(62, 62, 62))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rate, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(product, 0, 255, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avail, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)))
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DisplayDate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rateKeyReleased

        double quan = Integer.parseInt(quantity.getText());
        double rateS = Integer.parseInt(rate.getText());
        //double totalS
        total.setText(Double.toString(quan * rateS));

    }//GEN-LAST:event_rateKeyReleased
    private void Date() {
        Calendar now = Calendar.getInstance();
        int y = now.get(Calendar.YEAR);
        int m = (now.get(Calendar.MONTH)) + 1;
        int d = now.get(Calendar.DATE);
        DisplayDate.setText("Today's date is " + d + " / " + m + " / " + y);
        DisplayDate.setVisible(true);

    }

    private void populate() {
        product.removeAllItems();

        try {
            int Pindex = 0;
            int Sindex = 0;


            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vunafeeds", "root", "");
            Statement stmt = con.createStatement(ResultSet.TYPE_FORWARD_ONLY,
                    ResultSet.CONCUR_READ_ONLY);
            // product.removeAllItems();
            
            ResultSet rs;
            rs = stmt.executeQuery("Select * from product where Status = 'Active'");
                // System.out.println("Hello");

            Statement stmt3 = con.createStatement(ResultSet.TYPE_FORWARD_ONLY,
                    ResultSet.CONCUR_READ_ONLY);

            while (rs.next()) {
                String productS = rs.getString("productID");
                String productName = rs.getString("productName");
                pName.add(Pindex, productName);
                pNumber.add(Pindex, productS);

                ResultSet rs3 = stmt3.executeQuery("Select * from new_stock where productID = " + productS + " and Status = 'Current'");
                if (rs3.next()) {
                    String availableS = rs3.getString("Current");
                    //String productName = rs3.getString("productName");
                    available.add(Sindex, availableS);
                    //  pNumber.add(Sindex,productS); 
                    Sindex++;
                }
                Pindex++;
                product.addItem(productName);
            }
        } catch (SQLException e) {

            System.out.println("2 Error : " + e);
            JOptionPane.showMessageDialog(null, "Oops!! An error occured. \n " + e);
        } catch (Exception ex) {
            System.out.println("Error 1:" + ex);
            JOptionPane.showMessageDialog(null, "Oops!! An error occured. \n" + ex);
        }

    }
    private void productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productActionPerformed
        String productS = (String) product.getSelectedItem();
        //int pNum = pName.indexOf(productS);
        //available.get(pNum);
        try {
            for (int i = 0; i < pName.size(); i++) {
                if (productS.equals(pName.get(i))) {
                    avail.setText(available.get(i));
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No infromation on '" + productS + "' found");
            avail.setText("N/A");
        }
}//GEN-LAST:event_productActionPerformed

    private String[] addItemToTable() {
        String rateS = rate.getText();
        String quantityS = quantity.getText();
        String productS = (String) product.getSelectedItem();
        String totalS = total.getText();
        // particulars = null;
        String particulars[] = new String[5];

        if (rateS.length() == 0 || quantityS.length() == 0) {
            JOptionPane.showMessageDialog(null, "Please fill all fields");
        } else {
            int pNum = pName.indexOf(productS);

            String prodNum = pNumber.get(pNum);
            String availString = avail.getText();

            try {
                int availInt = Integer.parseInt(availString);
                int quantitiyInt = Integer.parseInt(quantityS);

                if (quantitiyInt > availInt) {
                    JOptionPane.showMessageDialog(null, "You cannot sell more than you have in store");
                } else {
                    try {
                        //System.out.println("Something was found 1");
                        particulars[0] = productS;
                        particulars[1] = quantityS;
                        particulars[2] = rateS;
                        particulars[3] = totalS;
                        particulars[4] = prodNum;

                        HomePage.toEdit = " ";
                    } catch (Exception ex) {
                        System.out.println("Error 1:" + ex);
                        JOptionPane.showMessageDialog(null, "Oops!! An error occured. \n" + ex);
                    }
                }
            } catch (NumberFormatException ne) {
                JOptionPane.showMessageDialog(null, "The units should be written in numeric format only. E.g  5 not five");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        return particulars;
    }

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        //String  = purchase.getText();
        // TODO add your handling code here:
}//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                SaleItemDialog dialog = new SaleItemDialog(new javax.swing.JFrame(), true, new JTable(), new ArrayList());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DisplayDate;
    public static javax.swing.JButton add;
    public static javax.swing.JTextField avail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JComboBox product;
    public static javax.swing.JFormattedTextField quantity;
    public static javax.swing.JFormattedTextField rate;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
